cat > .github/workflows/test.yml <<'YML'
name: Run Pytest with Report

on:
  push:
    branches: [ main, master ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-html pytest-cov

      - name: Run tests with report
        run: |
          pytest -v --html=report.html --self-contained-html --cov=your_module --cov-report=term

      - name: Upload HTML report
        uses: actions/upload-artifact@v4
        with:
          name: pytest-report
          path: report.html

      - name: Upload Coverage HTML
        if: always()
        run: pytest --cov=your_module --cov-report=html
      - name: Upload coverage artifact
        uses: actions/upload-artifact@v4
        with:
          name: coverage-html
          path: htmlcov/
YML
